version: '3.8'

services:
    mariadb:
        image: mariadb:10.11
        container_name: reservas-db
        restart: always
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: reservas
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
